baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "docsy"

[[menu.main]]
    name = "apis_services" 
    url = "/apis_services"

[[menu.main]]
    name = "reference" 
    url = "/reference"

# Site params

[params]

# Docsy: Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "007239566369470735695:624rglujm-w"

# Text label for the version menu in the top bar of the website.
version_menu = "master"

# The major.minor version tag for the version of the docs represented in this
# branch of the repository. Used in the "version-banner" partial to display a
# version number for this doc set.
version = "master"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
archived_version = false

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
#url_latest_version = "https://kubeflow.org/docs/"

# A variable used in various docs to determine URLs for config files etc.
# To find occurrences, search the repo for 'params "githubbranch"'.
#$githubbranch = "v1.1-branch"

# Add new release versions here. These entries appear in the drop-down menu
# at the top of the website.
[[params.versions]]
  version = "master"
  #githubbranch = "master"
  #url = "https://master.kubeflow.org"

[[params.versions]]
  version = "icefish"
  archived_version = true
  #githubbranch = "v0.5-branch"
  #url = "https://v0-5.kubeflow.org"

[[params.versions]]
  version = "halibut"
  archived_version = true
  #githubbranch = "v0.6-branch"
  #url = "https://v0-6.kubeflow.org"

[[params.versions]]
  version = "guppy"
  archived_version = true
  #githubbranch = "v0.7-branch"
  #url = "https://v0-7.kubeflow.org"

[[params.versions]]
  version = "flounder"
  archived_version = true
  #githubbranch = "v1.0-branch"
  #url = "https://v1-0-branch.kubeflow.org"

# Docsy: User interface configuration
[params.ui]
# Docsy: Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Docsy: Disable the search box in the side bar.
sidebar_search_disable = true
#  Docsy: Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
